version: '3.8'
services:
  hr-eureka-server:
    image: hr-eureka-server
    build: 
      dockerfile: Dockerfile
      context: ./hr-eurka-server
    ports:
      -8761:8761
         
  hr-api-gateway-zuul:
    image: hr-api-gateway-zuul
    build: 
      dockerfile: Dockerfilegit status
      context: ./hr-api-gateway-zuul
    depends_on: 
      - hr-eureka-server
    ports:
      -8765:8080

  hr-payroll:
    image: hr-payroll
    build:   
      dockerfile: Dockerfile 
      context: ./hr-payroll
    depends_on: 
      - hr-eureka-server
    restart: on-failure

  hr-worker:
    image: hr-worker
    build: 
      dockerfile: Dockerfile
      context: ./hr-worker                   
    depends_on: 
      - hr-eureka-server  
    restart: on-failure  

# Para o serviço que possui comunicação com o banco de dados em memória (H2), deverão ser iniciados 5 instâncias; 
# Para o serviço que não possui comunicação com o banco de dados memória (H2), deverão ser iniciados 2 instâncias; 
# docker-compose up -d --scale hr-worker=5 --scale hr-payroll=2